Sidekiq::Web v7.3.0-v7.3.6 does not have configure
See: sidekiq/sidekiq@cf7a879

```
Original Error: NoMethodError vendor/bundle/ruby/3.3.0/gems/sidekiq-scheduler-6.0.0/lib/sidekiq-scheduler/extensions/web.rb:4:in `<main>': undefined method `configure' for class Sidekiq::Web (NoMethodError)

Sidekiq::Web.configure do |cfg|
            ^^^^^^^^^^
        from sidekiq-scheduler-6.0.0/lib/sidekiq-scheduler/web.rb:59:in `require_relative'
        from sidekiq-scheduler-6.0.0/lib/sidekiq-scheduler/web.rb:59:in `<main>'
```

This fixes for Sidekiq::Web < v7.3.7